const PLAY_DESCRIPTIONS: Record<string, string> = {
  'strike': 'ストライク',
  'strike-swinging': '空振り',
  'strike-looking': '見逃し',
  'ball': 'ボール',
  'foul': 'ファール',
  'out-strikeout': '三振',
  'out-flyout': 'フライアウト',
  'out-groundout': 'ゴロアウト',
  'out-doublePlay': '併殺打',
  'out-sacrificeFly': '犠牲フライ',
  'out-sacrificeBunt': '犠牲バント',
  // New runner out descriptions
  'out-runnerOutFirst': '１塁ランナーアウト',
  'out-runnerOutSecond': '２塁ランナーアウト',
  'out-runnerOutThird': '３塁ランナーアウト',
  'out-doublePlayFirstSecond': '併殺（１塁・２塁）',
  'out-doublePlaySecondThird': '併殺（２塁・３塁）',
  'out-doublePlayFirstThird': '併殺（１塁・３塁）',
  'hit-single': 'シングルヒット',
  'hit-double': 'ツーベースヒット',
  'hit-triple': 'スリーベースヒット',
  'homerun': 'ホームラン',
  'walk': 'フォアボール',
  'hitByPitch': 'デッドボール',
  'steal': '盗塁成功',
  'caughtStealing': '盗塁死',
  'error': 'エラー',
  'wildPitch': 'ワイルドピッチ',
  'passedBall': 'パスボール',
  // Runner advance descriptions
  'advance-errorFirstToSecond': 'エラー進塁（１塁→２塁）',
  'advance-errorFirstToThird': 'エラー進塁（１塁→３塁）',
  'advance-errorFirstToHome': 'エラー進塁（１塁→ホーム）',
  'advance-errorSecondToThird': 'エラー進塁（２塁→３塁）',
  'advance-errorSecondToHome': 'エラー進塁（２塁→ホーム）',
  'advance-errorThirdToHome': 'エラー進塁（３塁→ホーム）',
  'advance-wildPitchFirstToSecond': 'WP進塁（１塁→２塁）',
  'advance-wildPitchFirstToThird': 'WP進塁（１塁→３塁）',
  'advance-wildPitchFirstToHome': 'WP進塁（１塁→ホーム）',
  'advance-wildPitchSecondToThird': 'WP進塁（２塁→３塁）',
  'advance-wildPitchSecondToHome': 'WP進塁（２塁→ホーム）',
  'advance-wildPitchThirdToHome': 'WP進塁（３塁→ホーム）',
  'advance-passedBallFirstToSecond': 'PB進塁（１塁→２塁）',
  'advance-passedBallFirstToThird': 'PB進塁（１塁→３塁）',
  'advance-passedBallFirstToHome': 'PB進塁（１塁→ホーム）',
  'advance-passedBallSecondToThird': 'PB進塁（２塁→３塁）',
  'advance-passedBallSecondToHome': 'PB進塁（２塁→ホーム）',
  'advance-passedBallThirdToHome': 'PB進塁（３塁→ホーム）',
};

export const getPlayDescription = (type: string, subType?: string): string => {
  const key = subType ? `${type}-${subType}` : type;
  return PLAY_DESCRIPTIONS[key] || type;
};
